name: Overleaf Pro Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ayaka-notes/overleaf

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
      - name: "Checkout Internal Overleaf Action"
        uses: actions/checkout@main
        with:
          repository: ayaka-notes/overleaf-internal
          ref: v6.0.0-ext-v3.3-git
          token: ${{secrets.ORGTOKEN}}
          path: './overleaf'
      - name: "Make CE Docker Image"
        run: |
          cd ./overleaf/server-ce
          make
          docker tag sharelatex/sharelatex:v6.0.0-ext-v3.3-git ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{env.DOCKER_REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
